name: Synchronize with SVN

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/15 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: sync files
        run: |
          svn co https://plugins.svn.wordpress.org/auto-comment-moderation/
          mkdir -p src
          cp -r auto-comment-moderation/trunk/* src/. 
          rm -rf auto-comment-moderation
          git config --global user.name "SVNBot"
          git config --global user.email "info@moderatehatespeech.com"
          git add .
          if [[ `git status --porcelain` ]]; then
            git commit -m "synchronize files"
            git push
          fi

          


