# This is a basic workflow to help you get started with Actions

name: Synchronnize with SVN

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/15 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        run: |
          svn co https://plugins.svn.wordpress.org/auto-comment-moderation/
          cd auto-comment-moderation
          cd trunk
          git config --global user.name "SVNBot"
          git config --global user.email "info@moderatehatespeech.com"
          git add .
          git commit -m "synchronize files"
          git push

